Add/fix links and Expo install step
emergentworks/project-not-911 pull request #54
Opened 2021-01-22 15:06 UTC by RodolfoNei

Issue: emergentworks#53

2021-01-22 17:31 UTC, rossPatton requested changes

2021-01-22 17:31 UTC, rossPatton commented on README.md
> +- Install dependencies: `npm install`
this actually should remain as `expo install`

`expo` is a react-native framework for doing cross-device apps. most of the time, it just does an `npm install`, but if in the future we want to use more native functionality, this will be important. `expo install` will also do the necessary setup for any packages we use that require additional native installs to work, if that makes sense!

2021-01-22 17:31 UTC, rossPatton commented on README.md
> +Assuming you have [node](https://nodejs.org/en/) installed on your machine:
👍

2021-01-22 17:32 UTC, rossPatton commented on README.md
> +- Install dependencies: `npm install`
on that note - it might be good to explain what Expo is in the documentation and how to set that up

2021-01-25 19:55 UTC, RodolfoNei commented on README.md
> +- Install dependencies: `npm install`
I see, I put `npm install` because with `expo install` in Ubuntu 20.04 I get this:
```
Command 'expo' not found, did you mean:

  command 'exo' from snap exoscale-cli (v1.22.2)
  command 'expr' from deb coreutils (8.30-3ubuntu2)
  command 'expn' from deb sendmail-base (8.15.2-18)

See 'snap info <snapname>' for additional versions.
```
And no further indication of what exactly I should do. However with a more detailed explanation of Expo in the documentation I think it will be ok. I will push a new commit with these changes!

2021-01-28 01:40 UTC, rossPatton commented on README.md
> +- Install dependencies: `npm install`
yeah, i believe expo needs to be installed globally for the command to be available like that, so that is a pre-requisite

2021-01-30 23:36 UTC, RodolfoNei commented
I pushed a new commit with the changes requested

2021-02-03 19:23 UTC, rossPatton approved these changes
thanks! this looks great!

2021-02-03 19:24 UTC, merged